import 'package:flutter/material.dart';
import '../services/auth_service.dart';

class RegisterScreen extends StatefulWidget { const RegisterScreen({super.key}); @override State<RegisterScreen> createState()=>_RegisterScreenState(); }
class _RegisterScreenState extends State<RegisterScreen> {
 final keyForm=GlobalKey<FormState>(); final name=TextEditingController(),email=TextEditingController(),pass=TextEditingController(),confirm=TextEditingController(); final auth=AuthService(); bool busy=false,accepted=false,hide=true;
 @override void dispose(){name.dispose();email.dispose();pass.dispose();confirm.dispose();super.dispose();}
 String? required_(String? v)=>v==null||v.trim().isEmpty?'Campo obligatorio':null;
 InputDecoration dec(String h,IconData i)=>InputDecoration(hintText:h,prefixIcon:Icon(i),filled:true,fillColor:Colors.white,contentPadding:const EdgeInsets.symmetric(horizontal:20,vertical:19),border:OutlineInputBorder(borderRadius:BorderRadius.circular(36),borderSide:const BorderSide(color:Color(0xFFBECAB9))),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(36),borderSide:const BorderSide(color:Color(0xFFBECAB9))));
 Widget field(TextEditingController c,String h,IconData i,{bool password=false,bool mail=false})=>TextFormField(controller:c,obscureText:password&&hide,keyboardType:mail?TextInputType.emailAddress:null,validator:(v){final r=required_(v);if(r!=null)return r;if(mail&&!RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$').hasMatch(v!.trim()))return'Correo inválido';if(password&&v!.length<6)return'Mínimo 6 caracteres';return null;},decoration:dec(h,i).copyWith(suffixIcon:password?IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility_off_outlined:Icons.visibility_outlined)):null));
 Future<void> create() async {if(!keyForm.currentState!.validate())return;if(!accepted){msg('Acepta los términos y la política de privacidad.');return;}setState(()=>busy=true);try{await auth.signUp(email.text,pass.text,name:name.text);if(mounted){msg('Cuenta creada. Revisa tu correo para confirmar.');Navigator.pop(context);}}catch(_){if(mounted)msg('No se pudo crear la cuenta. Inténtalo nuevamente.');}finally{if(mounted)setState(()=>busy=false);}}
 void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF8FAF8),appBar:AppBar(backgroundColor:const Color(0xFFF8FAF8),elevation:0,centerTitle:true,title:const Text('Crear una cuenta',style:TextStyle(fontWeight:FontWeight.w700))),body:Form(key:keyForm,child:ListView(padding:const EdgeInsets.fromLTRB(32,24,32,30),children:[const Center(child:CircleAvatar(radius:62,backgroundColor:Color(0xFFE9F4EC),child:Icon(Icons.pets,size:70,color:Color(0xFF006E1C)))),const SizedBox(height:14),const Center(child:Text('EIVET',style:TextStyle(fontSize:30,fontWeight:FontWeight.w700,color:Color(0xFF06322B)))),const SizedBox(height:30),field(name,'Nombre completo',Icons.person_outline),const SizedBox(height:16),field(email,'Correo electrónico',Icons.mail_outline,mail:true),const SizedBox(height:16),field(pass,'Contraseña',Icons.lock_outline,password:true),const SizedBox(height:16),TextFormField(controller:confirm,obscureText:hide,validator:(v)=>v!=pass.text?'Las contraseñas no coinciden':required_(v),decoration:dec('Confirmar contraseña',Icons.lock_reset)),const SizedBox(height:12),Row(children:[Checkbox(value:accepted,onChanged:(v)=>setState(()=>accepted=v??false)),const Expanded(child:Text('Acepto los Términos y condiciones y la Política de privacidad.'))]),const SizedBox(height:18),SizedBox(height:60,child:FilledButton(onPressed:busy?null:create,child:busy?const CircularProgressIndicator(color:Colors.white):const Text('Crear cuenta',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700)))),const SizedBox(height:18),Center(child:TextButton(onPressed:()=>Navigator.pop(context),child:const Text('¿Ya tienes una cuenta? Iniciar sesión')))])));
}
